// Mock data for the admin dashboard
// In production, this would come from the API endpoints

export const mockStats = {
  totalCustomers: 1247,
  totalEmployees: 12,
  activeEmployees: 10,
  totalPoints: 45890,
  totalPurchases: 8456,
  pendingInvitations: 3,
};

export const mockCustomers = [
  {
    id: "c1",
    full_name: "María García López",
    email: "maria.garcia@email.com",
    points_balance: 87,
    total_purchases: 156,
    redeemed_rewards: { coffees: [10, 20, 30, 40, 50, 60, 70, 80], meals: [25, 50, 75] },
    created_at: "2024-02-15T10:30:00Z",
  },
  {
    id: "c2",
    full_name: "Carlos Rodríguez",
    email: "carlos.r@email.com",
    points_balance: 64,
    total_purchases: 98,
    redeemed_rewards: { coffees: [10, 20, 30, 40, 50, 60], meals: [25, 50] },
    created_at: "2024-03-20T14:45:00Z",
  },
  {
    id: "c3",
    full_name: "Ana Martínez Soto",
    email: "ana.martinez@email.com",
    points_balance: 52,
    total_purchases: 78,
    redeemed_rewards: { coffees: [10, 20, 30, 40, 50], meals: [25, 50] },
    created_at: "2024-04-08T09:15:00Z",
  },
  {
    id: "c4",
    full_name: "Diego Fernández",
    email: "diego.f@email.com",
    points_balance: 45,
    total_purchases: 67,
    redeemed_rewards: { coffees: [10, 20, 30, 40], meals: [25] },
    created_at: "2024-05-12T16:20:00Z",
  },
  {
    id: "c5",
    full_name: "Laura Sánchez Ruiz",
    email: "laura.sanchez@email.com",
    points_balance: 38,
    total_purchases: 54,
    redeemed_rewards: { coffees: [10, 20, 30], meals: [25] },
    created_at: "2024-06-01T11:00:00Z",
  },
  {
    id: "c6",
    full_name: "Pablo Jiménez",
    email: "pablo.j@email.com",
    points_balance: 29,
    total_purchases: 42,
    redeemed_rewards: { coffees: [10, 20], meals: [25] },
    created_at: "2024-07-14T13:30:00Z",
  },
  {
    id: "c7",
    full_name: "Elena Torres",
    email: "elena.torres@email.com",
    points_balance: 22,
    total_purchases: 35,
    redeemed_rewards: { coffees: [10, 20], meals: [] },
    created_at: "2024-08-22T15:45:00Z",
  },
  {
    id: "c8",
    full_name: null,
    email: "guest.user@email.com",
    points_balance: 15,
    total_purchases: 28,
    redeemed_rewards: { coffees: [10], meals: [] },
    created_at: "2024-09-05T10:10:00Z",
  },
];

export const mockEmployees = [
  {
    id: "e1",
    email: "admin@vigocoffee.com",
    username: "admin",
    full_name: "Admin Principal",
    is_active: true,
    is_admin: true,
    created_at: "2024-01-01T08:00:00Z",
  },
  {
    id: "e2",
    email: "jose.hernandez@vigocoffee.com",
    username: "jose_h",
    full_name: "José Hernández",
    is_active: true,
    is_admin: false,
    created_at: "2024-02-10T09:30:00Z",
  },
  {
    id: "e3",
    email: "carmen.lopez@vigocoffee.com",
    username: "carmen_l",
    full_name: "Carmen López",
    is_active: true,
    is_admin: true,
    created_at: "2024-02-15T10:00:00Z",
  },
  {
    id: "e4",
    email: "miguel.santos@vigocoffee.com",
    username: "miguel_s",
    full_name: "Miguel Santos",
    is_active: true,
    is_admin: false,
    created_at: "2024-03-20T11:15:00Z",
  },
  {
    id: "e5",
    email: "sofia.reyes@vigocoffee.com",
    username: "sofia_r",
    full_name: "Sofía Reyes",
    is_active: false,
    is_admin: false,
    created_at: "2024-04-05T14:30:00Z",
  },
  {
    id: "e6",
    email: "andres.mora@vigocoffee.com",
    username: "andres_m",
    full_name: "Andrés Mora",
    is_active: true,
    is_admin: false,
    created_at: "2024-05-18T08:45:00Z",
  },
];

export const mockInvitations = [
  {
    id: "i1",
    email: "new.employee@email.com",
    token: "abc123xyz",
    expires_at: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    used_at: null,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "i2",
    email: "another.hire@email.com",
    token: "def456uvw",
    expires_at: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
    used_at: null,
    created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "i3",
    email: "pending.invite@email.com",
    token: "ghi789rst",
    expires_at: new Date(Date.now() + 12 * 60 * 60 * 1000).toISOString(),
    used_at: null,
    created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "i4",
    email: "completed.hire@email.com",
    token: "jkl012mno",
    expires_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    used_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "i5",
    email: "expired.invite@email.com",
    token: "pqr345stu",
    expires_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    used_at: null,
    created_at: new Date(Date.now() - 96 * 60 * 60 * 1000).toISOString(),
  },
];
